'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class FrmMiPerfil

    '''<summary>
    '''Head1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

    '''<summary>
    '''TituloPaginaWeb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TituloPaginaWeb As Global.System.Web.UI.HtmlControls.HtmlTitle

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''imagenresp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imagenresp As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''iraperfilmovil control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents iraperfilmovil As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''ImagenLogo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImagenLogo As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''irAPerfil control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents irAPerfil As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''UserPerfil control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UserPerfil As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''bienvenida control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bienvenida As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CboTipoDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CboTipoDoc As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TxtNumeroDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtNumeroDoc As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TxtFechaNac control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtFechaNac As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CboSexo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CboSexo As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''CboEstadoCivil control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CboEstadoCivil As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''CboNacionalidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CboNacionalidad As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''CboNivelFormacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CboNivelFormacion As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TxtCuil control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtCuil As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ImgPersonal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImgPersonal As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''btnSubirImgEmpleado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubirImgEmpleado As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''BtnDatosPersonles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnDatosPersonles As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''TxtCalle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtCalle As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TxtNumeroCalle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtNumeroCalle As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TxtPiso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPiso As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TxtDepto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtDepto As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TxtTelefonoFijo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtTelefonoFijo As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TxtTelefonMovil control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtTelefonMovil As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ComboRedes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ComboRedes As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TxtLinkRedsocial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtLinkRedsocial As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CboLocalidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CboLocalidad As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''BtnDatosDeContacto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnDatosDeContacto As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''RepeaterRedes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RepeaterRedes As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''TxtFechaDesde control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtFechaDesde As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ChkActivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChkActivo As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''TxtFechaHasta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtFechaHasta As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtEmpresa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtEmpresa As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtPuesto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPuesto As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''Combo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Combo As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''TxtDescrip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtDescrip As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''TxtDatosRef control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtDatosRef As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''TxtRefCoov control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtRefCoov As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''BtnRefLab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnRefLab As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''MisReferencias control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MisReferencias As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Grilla control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Grilla As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''TxtID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtApellidoGrupFam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtApellidoGrupFam As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtNombreGrupFam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtNombreGrupFam As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ComboPrentezco control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ComboPrentezco As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''TxtFechaNacGF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtFechaNacGF As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtOcupacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtOcupacion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BtnAgregarGrupoFam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnAgregarGrupoFam As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''TituloGF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TituloGF As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''GrillaGrupoFam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GrillaGrupoFam As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''TextBox4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtDesdeFA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtDesdeFA As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtHastaFA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtHastaFA As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ComboFA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ComboFA As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''ComboEspecilidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ComboEspecilidad As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''TxtInstitucion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtInstitucion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtTitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtTitulo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SubirRecibo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubirRecibo As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''BtnFormacionAca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnFormacionAca As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''H1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents H1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''GrillaFA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GrillaFA As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''TextBox6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtFechaDesdeCurso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtFechaDesdeCurso As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtFechaHastaCurso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtFechaHastaCurso As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtNombredelCurso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtNombredelCurso As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ComboCursos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ComboCursos As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''TxtHoras control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtHoras As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtInstitucionCursos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtInstitucionCursos As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtComentarios control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtComentarios As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BtnAgregarCurso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnAgregarCurso As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''H2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents H2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''GrillaCurso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GrillaCurso As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''TextBox7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''h3AntecedeSalud control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents h3AntecedeSalud As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''TxtAltura control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtAltura As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtPeso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPeso As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''EnfermedadSI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EnfermedadSI As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''EnfermedadNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EnfermedadNO As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''TxtTratamiento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtTratamiento As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cirugiaSi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cirugiaSi As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''CirugiaNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CirugiaNo As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''TxtCirugia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtCirugia As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BtnAgregarAntSalud control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnAgregarAntSalud As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''H3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents H3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''GridView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridView1 As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''TextBox10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox10 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Span8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Span8 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
